# MemoryPulse Configuration

# Base optimization interval in seconds (dynamically adjusted)
base_optimization_interval: 60

# Base buffer size in bytes (dynamically adjusted)
base_buffer_size: 1048576  # 1MB

# Default memory advice type (options: MADV_DONTNEED, MADV_WILLNEED, MADV_SEQUENTIAL, MADV_RANDOM)
default_madvise_type: "MADV_DONTNEED"

# Memory threshold for dynamic adjustments (in MB)
memory_threshold: 100

# Packet rate threshold for adjustments (packets per second)
packet_rate_threshold: 50

# Enable OPcache reset if available
enable_opcache_reset: true

# Log level (0 = none, 1 = basic, 2 = detailed)
log_level: 1
