name: MemoryPulse
api: [5.0.0]
version: 1.0.0
main: MemoryPulse\Main
description: "A plugin that dynamically optimizes server memory and packet handling."
author: Estem0

permissions:
  memorypulse.bypass:
    description: "Allows bypassing optimization restrictions (for debugging)."
    default: op
