# Enable or disable the plugin
enabled: true

# Base optimization interval in seconds (will be dynamically adjusted)
interval: 60

# Base memory buffer size in bytes (will be dynamically adjusted)
buffer-size: 1048576  # 1MB

# Initial memory threshold in MB (will adapt)
memory-threshold: 100

# Initial packet rate threshold (packets per second, will adapt)
packet-threshold: 50

# Default memory advice type (MADV_DONTNEED, MADV_WILLNEED, MADV_SEQUENTIAL, MADV_RANDOM)
default-madvise: "MADV_DONTNEED"

# Enable OPcache reset if available
opcache-reset: true

# Enable plugin logger
logger: false
